stages:          # List of stages for jobs, and their order of execution
  - build

variables:
  CCACHE_BASEDIR: $CI_PROJECT_DIR
  CCACHE_DIR: $CI_PROJECT_DIR/ccache

cache:
    key: ccache_main # this is the global location.
    paths:
      - $CCACHE_DIR
build-job:       # This job runs in the build stage, which runs first.
  stage: build

  before_script:
    - export CCACHE_BASEDIR="$PWD"
    - export CCACHE_DIR="$PWD/ccache"
    - export CCACHE_COMPILERCHECK=content
    - ccache --zero-stats || true
    - ccache --show-stats || true
  after_script:
    - export CCACHE_DIR="$PWD/ccache"
    - ccache --show-stats

  script:
    - echo "Compiling the code..."
    - make -f makefile.libra allclone
    - make Kokkos_CUDA_ARCH=Kokkos_ARCH_VOLTA70 -f makefile.libra allbuild
    - echo "Compile complete."
