stages:
  - build
  - test
  - production

variables:
  GIT_CLEAN_FLAGS: none

build-job:
  stage: build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[ci build\]/'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
    - changes:
        - README.md
        - scripts/**/*
        - doc/**/*
  before_script:
    - export CCACHE_BASEDIR="$PWD"
    - export CCACHE_DIR="$PWD/ccache"
    - export CCACHE_COMPILERCHECK=content
    - ccache --zero-stats || true
    - ccache --show-stats || true
    - git clean -ffdx

  script:
    - echo "Compiling the code..."
    - echo $PATH
    - nvidia-smi
    - which nvcc
    - mkdir build
    - cd build
    - cmake -DApps_BUILD_TESTS=ON -DKokkos_CUDA_ARCH_NAME=Kokkos_ARCH_VOLTA70 ..
    - make
    - echo "Compile complete."

test-job:
  stage: test
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[ci build\]/'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
    - changes:
        - README.md
        - scripts/**/*
        - doc/**/*
  script:
    - echo $PWD
    - base_path=$PWD
    - echo "Entering $PWD/build/Libra/apps/src/tests to run apps unit tests"
    - cd ${base_path}/apps/src/tests
    - ${base_path}/build/Libra/apps/src/tests/LibRATests --gtest_output="xml:report.xml"

  artifacts:
    when: always
    reports:
      junit: ${base_path}/build/Libra/apps/src/tests/report.xml

production-job:
  stage: production
  only:
    - manual
  script:
    - echo "Deploying to production..."
    # Add your deployment commands here
