# HPG external project
include(ExternalProject)

ExternalProject_Add(
  Hpg
  GIT_REPOSITORY ${LIBRA_HPG_GIT_REPOSITORY}
  GIT_TAG        ${LIBRA_HPG_GIT_TAG}
  DEPENDS        Kokkos FFTW_double
  SOURCE_DIR     ${CMAKE_SOURCE_DIR}/dependencies/HPG
  BINARY_DIR     ${BUILD_DIR}/HPG
  CONFIGURE_COMMAND PKG_CONFIG_PATH=${INSTALL_DIR}/lib/pkgconfig:$ENV{PKG_CONFIG_PATH} CMAKE_PREFIX_PATH=${INSTALL_DIR}:${CMAKE_PREFIX_PATH}:${INSTALL_DIR}/lib/cmake/Kokkos
                    ${CMAKE_COMMAND} <SOURCE_DIR> -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_BINDIR=bin/Hpg -DCMAKE_BUILD_TYPE=Release
                    -DFFTW_LIBRARIES=${INSTALL_DIR}/lib/ -DFFTW_ROOT=${INSTALL_DIR} -DHpg_ENABLE_MIXED_PRECISION=OFF -DHpg_ENABLE_EXPERIMENTAL_IMPLEMENTATIONS=OFF -DHpg_API=17
                    -DHpg_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER=${INSTALL_DIR}/bin/kokkos/nvcc_wrapper
                    -DKokkos_DIR=${INSTALL_DIR}/lib/cmake/Kokkos ${CCACHE_LAUNCHER}
  BUILD_COMMAND   make -j ${NCORES}
  INSTALL_COMMAND make install
)
