#!/bin/bash
# Copyright (C) 2024
# Associated Universities, Inc. Washington DC, USA.
#
# This library is free software; you can redistribute it and/or modify it
# under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Library General Public
# License for more details.is
#
# You should have received a copy of the GNU Library General Public License
# along with this library; if not, write to the Free Software Foundation,
# Inc., 675 Massachusetts Ave, Cambridge, MA 02139, USA.
#
# Correspondence concerning this should be addressed as follows:
#        Postal address: National Radio Astronomy Observatory
#                        1003 Lopezville Road,
#                        Socorro, NM - 87801, USA
#
# $Id$


usage()
{
    echo "Usage: $0 [-s <save logs location>] [-h]"$'\n'\
	 "       -s (optional) is the location where the user wants to save existing logs before cleanup."$'\n'\
	 "       -h prints help and exits"$'\n\n'\
	 "       Example: $0 -s 20151021.logs"$'\n'
}


# Begin execution


while getopts "s:h" option; do
    case "$option" in
        s) savelogsdir=${OPTARG} ;;
	h) usage
	   exit 0 ;;
	*) echo "${option}: Unknown option"
	   usage
	   exit 1 ;;
    esac
done

cleanupextlist="*.log *.dag.* logs.* *.std*"

if [ ! -z ${savelogsdir} ]
then
    mkdir ${savelogsdir}
    cp ${cleanupextlist} ${savelogsdir}
fi


rm -rf ${cleanupextlist}
